import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
import { ChatProvider } from "@/context/ChatContext";
import Navbar from "@/components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
  alternates: {
    languages: {
      en: "/en",
      ur: "/ur",
    },
  },
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <ChatProvider>
          <Navbar />
          {children}
        </ChatProvider>
      </body>
    </html>
  );
}
